package destiny:user;

interface destiny-user-api {
    use destiny:common/types.{store-name, user};

    variant error {
        already-exists
    }

    stores: func() -> list<store-name>;
    create-store: func(name: store-name) -> result<_, error>;

    // Hack to proxy request to destiny:accounts
    get-user-name: func(email: string) -> user;
}

world destiny-user {
    export destiny-user-api;

    import destiny:common/types;
}
